::  Brief       : This is a batch script file for deleting the unnecessary files
::              : generated by Vivado. The shell script shouldn't be used unless
::              : there is another way to generate the same files such as Tickle.
::  Author      : Caglayan DOKME, caglayandokme@gmail.com
::  Date        : September 20, 2020
::  Note        : User can either run the script inside the directory to be cleaned
::              : or give the project name as an input to the program
::  Example     : Running in the same directory
::              :   ./ClearDirectory.bat SharedBram
::              : Running from another directory (full path)
::              :   ./ClearDirectory.bat SharedBram /path/to/project/

@ECHO OFF

:: Parse the program arguments
:: First input is the project name
:: Second input is the full project path
if not "%1" == "" (
    set projectName=%1
    
    if not "%2" == "" (
        set projectPath=%2
        
        :: Check if the project path is valid
        if not exist %projectPath% (
            echo ERROR: Given path %2 is invalid!
        )
        
        if not "%3" == "" (
            msg Too many input arguments given.
            
            timeout 3 >nul
            exit
        )
    ) else (
        :: If second argument is empty, then we can use the current directory
        set projectPath=%~dp0    
    )
) else (
    msg At least the project name is required!
    
    timeout 3 >nul
    exit
)

:: Derive the base name for folders and files to be removed
if "%projectPath:~-1%" == "\" (
    set baseName=%projectPath%%projectName%
) else (
    set baseName=%projectPath%\%projectName%
)

echo Project path: %projectPath%
echo Project name: %projectName%
echo Base name: %baseName%

:: Delete the .srcs folder
if exist %baseName%.srcs\ (
    echo srcs folder deleted!
    
    rmdir /s/q %baseName%.srcs
)

:: Delete the .cache folder
if exist %baseName%.cache\ (
    echo cache folder deleted!
    
    rmdir /s/q %baseName%.cache
)

:: Delete the .hw folder
if exist %baseName%.hw\ (
    echo hw folder deleted!
    
    rmdir /s/q %baseName%.hw
)

:: Delete the .ip_user_files folder
if exist %baseName%.ip_user_files\ (
    echo ip_user_files folder deleted!
    
    rmdir /s/q %baseName%.ip_user_files
)

:: Delete the .sim folder
if exist %baseName%.sim\ (
    echo sim folder deleted!
    
    rmdir /s/q %baseName%.sim
)

:: Delete the .runs folder
if exist %baseName%.runs\ (
    echo runs folder deleted!
    
    rmdir /s/q %baseName%.sim
)

:: Delete the .Xil folder
if exist %projectPath%\.Xil\ (
    echo .Xil folder deleted!
    
    rmdir /s/q %projectPath%\.Xil
)

:: Delete the .Xil folder
if exist %projectPath%.Xil\ (
    echo .Xil folder deleted!
    
    rmdir /s/q %projectPath%.Xil
)

:: Delete the .xpr project file
if exist %baseName%.xpr (
    echo .xpr file deleted!
    
    del %baseName%.xpr
)


