#!/bin/bash
# Brief     : This is a shell script file for deleting the unnecessary files
#           : generated by Vivado. The shell script shouldn't be used unless
#           : there is another way to generate the same files such as Tickle.
# Author    : Caglayan DOKME, caglayandokme@gmail.com
# Date      : September 19, 2020
# Note      : User can either run the script inside the directory to be cleaned
#           : or give the project name as an input to the program
# Example   : Running in the same directory
#           :   ./ClearDirectory.sh SharedBram
#           : Running from another directory (full path)
#           :   ./ClearDirectory.sh SharedBram /path/to/project/

# At least one input parameter needed
if [ $# -gt 0 ]; then
    projectName=$1      # Fetch the project name

    # If another input is given, it must be the project path(full)
    if [ $# -gt 1 ]; then
        # Check if the directory exists
        if [ -d "$2" ]; then
            echo "Given project path $2 is valid."

            projectPath=$2

            if [ $# -gt 2 ]; then
                echo "Too many($#) input parameters."

                exit
            fi
        else
        	echo "ERROR: Given path $2 is invalid!"

            exit
        fi
    else
        projectPath=$(pwd)
    fi
else
    echo "No project name given to program!"

    exit
fi

# Derive the base name for folders and files to be removed
fullName=${projectPath}/${projectName}

# Delete the .xpr project file
if [ -e "${fullName}.xpr" ]; then
    rm ${fullName}.xpr

    echo ".xpr file deleted!"
fi

# Delete the .cache folder
if [ -d "${fullName}.cache" ]; then
    rm -r ${fullName}.cache

    echo ".cache folder deleted!"
fi

# Delete the .hw folder
if [ -d "${fullName}.hw" ]; then
    rm -r ${fullName}.hw

    echo ".hw folder deleted!"
fi

# Delete the .ip_user_files folder
if [ -d "${fullName}.ip_user_files" ]; then
    rm -r ${fullName}.ip_user_files

    echo ".ip_user_files folder deleted!"
fi

# Delete the .sim folder
if [ -d "${fullName}.sim" ]; then
    rm -r ${fullName}.sim

    echo ".sim folder deleted!"
fi

# Delete the .srcs folder
if [ -d "${fullName}.srcs" ]; then
    rm -r ${fullName}.srcs

    echo ".srcs folder deleted!"
fi

# Delete the .runs folder
if [ -d "${fullName}.runs" ]; then
    rm -r ${fullName}.runs

    echo ".runs folder deleted!"
fi
