# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ArtyA7.xdc

# Block Designs: bd/mainBd/mainBd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd || ORIG_REF_NAME==mainBd} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_microblaze_0_0/mainBd_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_microblaze_0_0 || ORIG_REF_NAME==mainBd_microblaze_0_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_mdm_1_0/mainBd_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_mdm_1_0 || ORIG_REF_NAME==mainBd_mdm_1_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_clk_wiz_1_0/mainBd_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_clk_wiz_1_0 || ORIG_REF_NAME==mainBd_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_rst_clk_wiz_1_100M_0/mainBd_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mainBd_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_xlconstant_0_0/mainBd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_xlconstant_0_0 || ORIG_REF_NAME==mainBd_xlconstant_0_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_dlmb_v10_0/mainBd_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_dlmb_v10_0 || ORIG_REF_NAME==mainBd_dlmb_v10_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_ilmb_v10_0/mainBd_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_ilmb_v10_0 || ORIG_REF_NAME==mainBd_ilmb_v10_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_dlmb_bram_if_cntlr_0/mainBd_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mainBd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_ilmb_bram_if_cntlr_0/mainBd_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mainBd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_lmb_bram_0/mainBd_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_lmb_bram_0 || ORIG_REF_NAME==mainBd_lmb_bram_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_axi_interconnect_0_0/mainBd_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_axi_interconnect_0_0 || ORIG_REF_NAME==mainBd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_axi_interconnect_0_1/mainBd_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_axi_interconnect_0_1 || ORIG_REF_NAME==mainBd_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_axi_gpio_0_0/mainBd_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_axi_gpio_0_0 || ORIG_REF_NAME==mainBd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_axi_uartlite_0_0/mainBd_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_axi_uartlite_0_0 || ORIG_REF_NAME==mainBd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_xbar_1/mainBd_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_xbar_1 || ORIG_REF_NAME==mainBd_xbar_1} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_xbar_0/mainBd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_xbar_0 || ORIG_REF_NAME==mainBd_xbar_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_mig_7series_0_1/mainBd_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_mig_7series_0_1 || ORIG_REF_NAME==mainBd_mig_7series_0_1} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_util_vector_logic_0_0/mainBd_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_util_vector_logic_0_0 || ORIG_REF_NAME==mainBd_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/mainBd/ip/mainBd_auto_cc_0/mainBd_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBd_auto_cc_0 || ORIG_REF_NAME==mainBd_auto_cc_0} -quiet] -quiet

# XDC: bd/mainBd/mainBd_ooc.xdc
